openapi: 3.0.0
info:
  title: Arduino LED Control API
  version: 1.0.0
  description: API για έλεγχο LED και διαχείριση χρηστών (Admin)

servers:
  - url: http://localhost:5000
    description: Local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    post:
      summary: Σύνδεση χρήστη
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: 1234
      responses:
        '200':
          description: Επιστρέφει JWT token και στοιχεία χρήστη
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      _id:
                        type: string
                      username:
                        type: string
                      role:
                        type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /auth/profile:
    get:
      summary: Προβολή προφίλ χρήστη
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Επιστρέφει τα στοιχεία χρήστη χωρίς το password
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  username:
                    type: string
                  role:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /user:
    post:
      summary: Δημιουργία νέου χρήστη (Admin)
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: newuser
                password:
                  type: string
                  example: 1234
                role:
                  type: string
                  enum: [user, admin]
                  example: user
      responses:
        '201':
          description: Ο χρήστης δημιουργήθηκε επιτυχώς
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  username:
                    type: string
                  role:
                    type: string
        '400':
          description: Σφάλμα δημιουργίας χρήστη
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /led/on:
    get:
      summary: Άναμμα LED
      tags:
        - LED
      security:
        - bearerAuth: []
      responses:
        '200':
          description: LED άναψε
          content:
            text/plain:
              schema:
                type: string
                example: LED is ON
        '500':
          description: Σφάλμα κατά το άναμμα
          content:
            text/plain:
              schema:
                type: string
                example: Error turning on LED

  /led/off:
    get:
      summary: Σβήσιμο LED
      tags:
        - LED
      security:
        - bearerAuth: []
      responses:
        '200':
          description: LED έσβησε
          content:
            text/plain:
              schema:
                type: string
                example: LED is OFF
        '500':
          description: Σφάλμα κατά το σβήσιμο
          content:
            text/plain:
              schema:
                type: string
                example: Error turning off LED
